# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cache_pb2 as proto_dot_cache__pb2


class CacheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendJSON = channel.unary_unary(
                '/cache.Cache/SendJSON',
                request_serializer=proto_dot_cache__pb2.JSONRequest.SerializeToString,
                response_deserializer=proto_dot_cache__pb2.JSONResponse.FromString,
                )
        self.GetData = channel.unary_unary(
                '/cache.Cache/GetData',
                request_serializer=proto_dot_cache__pb2.DataRequest.SerializeToString,
                response_deserializer=proto_dot_cache__pb2.DataResponse.FromString,
                )


class CacheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendJSON(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendJSON': grpc.unary_unary_rpc_method_handler(
                    servicer.SendJSON,
                    request_deserializer=proto_dot_cache__pb2.JSONRequest.FromString,
                    response_serializer=proto_dot_cache__pb2.JSONResponse.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=proto_dot_cache__pb2.DataRequest.FromString,
                    response_serializer=proto_dot_cache__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.Cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cache(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendJSON(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.Cache/SendJSON',
            proto_dot_cache__pb2.JSONRequest.SerializeToString,
            proto_dot_cache__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.Cache/GetData',
            proto_dot_cache__pb2.DataRequest.SerializeToString,
            proto_dot_cache__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
