# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/cache.proto\x12\x05\x63\x61\x63he\" \n\x0bJSONRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"\x1f\n\x0cJSONResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x05\"\x0e\n\x0c\x44\x61taResponse2p\n\x05\x43\x61\x63he\x12\x33\n\x08SendJSON\x12\x12.cache.JSONRequest\x1a\x13.cache.JSONResponse\x12\x32\n\x07GetData\x12\x12.cache.DataRequest\x1a\x13.cache.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JSONREQUEST']._serialized_start=28
  _globals['_JSONREQUEST']._serialized_end=60
  _globals['_JSONRESPONSE']._serialized_start=62
  _globals['_JSONRESPONSE']._serialized_end=93
  _globals['_DATAREQUEST']._serialized_start=95
  _globals['_DATAREQUEST']._serialized_end=125
  _globals['_DATARESPONSE']._serialized_start=127
  _globals['_DATARESPONSE']._serialized_end=141
  _globals['_CACHE']._serialized_start=143
  _globals['_CACHE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
