version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  grpc_server:
    build: 
      context: ./server
      dockerfile: Dockerfile.grpc_server
    ports:
      - "50051:50051"
    depends_on:
      - redis

  grpc_client:
    build:
      context: ./client
      dockerfile: Dockerfile.grpc_client
    depends_on:
      - grpc_server
